import type { PenjahitComputedRow } from "@/lib/payroll-penjahit";
import type { PartimeComputedRow } from "@/lib/payroll-partime";
import type { AdminPayrollSummarySheetRow } from "@/lib/payroll-summary";

// Partime -> baris slip gaji. Komponen: insentif x hari masuk, uang makan x hari masuk,
// tunjangan jabatan, subsidi, BPJS; potongan hanya telat (Rp5.000/telat). Tidak ada
// kontrak/pinjaman/kerajinan/lembur.
export function mapPartimeRow(r: PartimeComputedRow): AdminPayrollSummarySheetRow {
  return {
    id: r.payrollId,
    employeeId: r.employeeId,
    number: 0,
    name: r.nama,
    role: r.jabatan,
    division: r.divisi,
    recapGroup: "",
    unit: null,
    pembebanan: null,
    penempatan: null,
    department: r.departemen,
    bank: r.bank,
    accountNumber: r.noRekening,
    payrollType: "non_sales",
    monthlyBaseSalary: r.totalGaji,
    dailyBaseSalary: r.insentifPerHari,
    positionAllowance: r.tunjanganJabatan,
    fixedMealAllowance: r.uangMakanPerHari,
    subsidy: r.subsidi,
    fixedDiligenceAllowance: 0,
    bpjs: r.bpjs,
    performanceBonus: 0,
    transportAllowance: 0,
    incentive: 0,
    vehicleAllowance: 0,
    travelReimbursement: 0,
    workDays: r.hariTetap,
    presentDays: r.masuk,
    totalBaseSalary: r.insentifTotal,
    omzetBonus: 0,
    mealAllowance: r.uangMakanTotal,
    diligenceAllowance: 0,
    overtimeHours: 0,
    overtimeBonus: 0,
    leaveCount: 0,
    sickCount: 0,
    sickWithoutNoteCount: 0,
    halfDayCount: 0,
    halfDayDeduction: 0,
    lateCount: r.telat,
    lateDeduction: r.potonganTelat,
    totalSalary: r.totalGaji,
    totalSalaryBeforeDeduction: r.totalGajiSebelumPotongan,
    contractDeduction: 0,
    companyLoan: 0,
    personalLoan: 0,
    remainingLoanBalance: 0,
    fineDeduction: r.potonganTelat,
    contractCut: 0,
    loanCut: 0,
    diligenceCut: 0,
    otherDeduction: 0,
    otherDeductionNote: null,
    contractReturn: 0,
    netIncome: r.totalGaji,
    inputGajiPerDay: r.inputInsentifPerHari,
    inputTunjanganJabatan: r.inputTunjanganJabatan,
    inputUangMakan: r.inputUangMakanPerHari,
    inputSubsidi: r.inputSubsidi,
    inputUangKerajinan: 0,
    inputBpjs: r.inputBpjs,
    inputBonusPerforma: 0,
    inputInsentif: 0,
    inputUangTransport: 0,
    inputKendaraan: 0,
    inputPerjalananDinasReimburse: 0,
    inputOverrideMasuk: null,
    inputOverrideLembur: null,
    inputOverrideIzin: null,
    inputOverrideSakit: null,
    inputOverrideSakitTanpaSurat: null,
    inputOverrideSetengahHari: null,
    inputOverrideKontrak: null,
    inputOverridePinjaman: null,
    inputOverridePinjamanPribadi: null,
    inputOverrideGajiPokok: null,
    inputOverridePotonganAbsensi: null,
    inputPotonganSp2: null,
    freelanceRateType: "per_hari",
    inputGajiPerJam: 0,
  };
}

export function mapPenjahitRow(row: PenjahitComputedRow): AdminPayrollSummarySheetRow {
  return {
    id: row.payrollId,
    employeeId: row.employeeId,
    number: 0,
    name: row.nama,
    role: row.jabatan,
    division: row.divisi,
    recapGroup: row.pembagianRekapan ?? "",
    unit: null,
    pembebanan: null,
    penempatan: null,
    department: row.departemen,
    bank: row.bank,
    accountNumber: row.noRekening,
    payrollType: "penjahit",
    penjahitInfo: {
      tipe: row.tipePayroll,
      pencairan: row.pencairan,
    },
    monthlyBaseSalary: row.gajiPokokMonthly,
    dailyBaseSalary: row.gajiPokokPerHari,
    positionAllowance: row.tunjanganJabatan,
    fixedMealAllowance: row.uangAbsensiPerHari,
    subsidy: 0,
    fixedDiligenceAllowance: row.uangKerajinanNominal,
    bpjs: row.bpjs,
    performanceBonus: row.bonusPerforma,
    transportAllowance: 0,
    incentive: 0,
    vehicleAllowance: 0,
    travelReimbursement: 0,
    workDays: row.hariKerja,
    presentDays: row.masuk,
    totalBaseSalary: row.totalGajiPokok,
    omzetBonus: 0,
    mealAllowance: row.uangAbsensiTotal,
    diligenceAllowance: row.kerajinanEarned,
    overtimeHours: row.lemburJam,
    overtimeBonus: row.bonusLembur,
    leaveCount: row.izin,
    sickCount: row.sakit,
    sickWithoutNoteCount: row.sakitTanpaSurat,
    halfDayCount: row.setengahHari,
    halfDayDeduction: row.potonganSetengahHari,
    lateCount: row.telat,
    lateDeduction: row.potonganTelat,
    totalSalary: row.totalGaji,
    totalSalaryBeforeDeduction: row.totalGajiSebelumPotongan,
    contractDeduction: row.potonganKontrak,
    companyLoan: row.potonganPinjaman,
    personalLoan: row.potonganLainLain,
    remainingLoanBalance: row.remainingLoanBalance,
    fineDeduction: row.potonganDenda,
    contractCut: row.potonganKontrak,
    loanCut: row.potonganPinjaman + row.potonganLainLain,
    // diligenceCut (kerajinan hangus) diturunkan dari potonganDenda AKTUAL, bukan dari
    // (uangKerajinanNominal - kerajinanEarned) auto. Sebab: bila denda penjahit di-OVERRIDE
    // manual, potonganDenda (fineDeduction) berubah tapi komponen auto tidak, sehingga
    // Pencairan (telat+1/2hari+kerajinan) ≠ Pembagian (fineDeduction) -> tabel tidak balance.
    // Dengan rumus ini telat + 1/2hari + kerajinan = potonganDenda selalu (saat auto = kerajinan
    // hangus asli; saat override = kerajinan menyerap selisih). Kedua tabel konsisten.
    diligenceCut: row.potonganDenda - row.potonganSetengahHari - row.potonganTelat,
    otherDeduction: 0,
    otherDeductionNote: null,
    netIncome: row.penerimaanBersih,
    inputGajiPerDay: row.inputGajiPerDay,
    inputTunjanganJabatan: row.inputTunjanganJabatan,
    inputUangMakan: row.inputUangMakan,
    inputSubsidi: 0,
    inputUangKerajinan: row.inputUangKerajinan,
    inputBpjs: row.inputBpjs,
    inputBonusPerforma: row.inputBonusPerforma,
    inputInsentif: 0,
    inputUangTransport: 0,
    inputKendaraan: 0,
    inputPerjalananDinasReimburse: 0,
    inputOverrideMasuk: row.inputOverrideMasuk,
    inputOverrideLembur: row.inputOverrideLembur,
    inputOverrideIzin: row.inputOverrideIzin,
    inputOverrideSakit: row.inputOverrideSakit,
    inputOverrideSakitTanpaSurat: row.inputOverrideSakitTanpaSurat,
    inputOverrideSetengahHari: row.inputOverrideSetengahHari,
    inputOverrideKontrak: row.inputOverrideKontrak,
    inputOverridePinjaman: row.inputOverridePinjaman,
    inputOverridePinjamanPribadi: row.inputPotonganLainLain,
    inputOverrideGajiPokok: row.inputOverrideGajiPokok,
    inputOverridePotonganAbsensi: null,
    inputPotonganSp2: null,
    contractReturn: row.contractReturn,
    freelanceRateType: "per_hari",
    inputGajiPerJam: 0,
  };
}
